### ISSUE TITLE
Could you please add a license?

### ISSUE THREAD

**Issue by yml** [samuel/go-librato#2]
I would like to use this lib to push data to librato but I can't because the license is missing.

Thank you

**Comment by samuel** [comment]
Definitely, I added a 3-clause BSD license to the repo. Hope you find the pkg useful!

-
Samuel

**Comment by yml** [comment]
Thank you. I found it useful I am going to use it to push [Freckle's data )(https://letsfreckle.com) to librato.

* https://github.com/yml/freckle-project-indicators
